# Generated by Django 4.2.5 on 2025-10-01 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField()),
                ('version_software', models.CharField(max_length=50)),
                ('responsable', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Codigo_oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('terminal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contactanos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('correo', models.CharField(max_length=255, null=True)),
                ('asunto', models.CharField(max_length=255, null=True)),
                ('mensaje', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Corresponsal_consignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('banco', models.CharField(max_length=100)),
                ('fecha_consignacion', models.DateField()),
                ('fecha', models.DateTimeField()),
                ('responsable', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=20)),
                ('detalle', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('codigo_incocredito', models.CharField(max_length=100, null=True)),
                ('detalle_banco', models.TextField(null=True)),
                ('min', models.CharField(blank=True, max_length=20, null=True)),
                ('imei', models.CharField(blank=True, max_length=30, null=True)),
                ('planilla', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, null=True, unique=True)),
                ('titulo', models.CharField(max_length=255, null=True)),
                ('detalle', models.CharField(max_length=255, null=True)),
                ('precio', models.CharField(max_length=255, null=True)),
                ('carpeta', models.CharField(max_length=255, null=True)),
                ('marca', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lista_negra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.CharField(max_length=255, unique=True)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Permisos_precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.CharField(max_length=255, unique=True)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Porcentaje_comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('valor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('detalle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReporteDetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('imei', models.CharField(max_length=50, unique=True)),
                ('modelo_equipo', models.CharField(max_length=255)),
                ('sucursal', models.CharField(max_length=100)),
                ('tipo_producto', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_venta_original', models.CharField(max_length=100)),
                ('asesor', models.CharField(blank=True, max_length=150, null=True)),
                ('canal', models.CharField(blank=True, max_length=100, null=True)),
                ('tiket_venta', models.CharField(blank=True, max_length=100, null=True)),
                ('costo_equipo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('incentivo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('clasificacion_venta', models.CharField(max_length=50)),
                ('tipo_vendedor', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Detalle de Venta para Reporte',
                'verbose_name_plural': 'Detalles de Venta para Reportes',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Traducciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=255, unique=True)),
                ('stok', models.CharField(max_length=255)),
                ('iva', models.BooleanField()),
                ('active', models.BooleanField()),
                ('tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transacciones_sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establecimiento', models.CharField(max_length=100)),
                ('codigo_aval', models.CharField(max_length=100)),
                ('codigo_incocredito', models.CharField(max_length=100)),
                ('terminal', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('hora', models.CharField(max_length=100)),
                ('nombre_convenio', models.CharField(max_length=100)),
                ('operacion', models.CharField(max_length=100)),
                ('fact_cta', models.CharField(max_length=100)),
                ('cod_aut', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('esquema', models.CharField(max_length=100)),
                ('numero_tarjeta', models.CharField(max_length=100)),
                ('comision', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Variables_prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('formula', models.TextField(null=True)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.permisos_precio')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable_corresponsal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.codigo_oficina')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Permisos_usuarios_precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_permiso', models.BooleanField()),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.permisos_precio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Permisos_usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_permiso', models.BooleanField()),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.permisos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_asignada', models.CharField(blank=True, default=None, help_text='Ruta asignada al usuario si tiene el rol de asesor.', max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PagoComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idpos', models.CharField(db_index=True, max_length=100)),
                ('punto_de_venta', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('monto_total_pagado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_comisiones', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodos_pago', models.JSONField()),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lista_precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100, null=True)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='intranet.carga')),
            ],
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('formula', models.TextField(null=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('price_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intranet.permisos_precio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asesor_identificador', models.CharField(db_index=True, help_text='Nombre del asesor, tal como viene en el archivo Excel.', max_length=250)),
                ('iccid', models.CharField(db_index=True, max_length=22)),
                ('distribuidor', models.CharField(blank=True, max_length=150, null=True)),
                ('producto', models.CharField(blank=True, max_length=100, null=True)),
                ('co_id', models.CharField(blank=True, max_length=50, null=True)),
                ('prim_llamada_activacion', models.DateField(blank=True, null=True)),
                ('min', models.CharField(blank=True, max_length=50, null=True)),
                ('idpos', models.CharField(db_index=True, max_length=50)),
                ('punto_de_venta', models.CharField(max_length=200)),
                ('ruta', models.CharField(blank=True, max_length=100, null=True)),
                ('comision_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pago', models.CharField(blank=True, max_length=100, null=True)),
                ('mes_liquidacion', models.DateField(blank=True, null=True)),
                ('mes_pago', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Acumulada', 'Acumulada'), ('Pagada', 'Pagada')], db_index=True, default='Pendiente', max_length=20)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('asesor', models.ForeignKey(blank=True, help_text='Vínculo al usuario de Django si se encuentra una coincidencia.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comisiones', to=settings.AUTH_USER_MODEL)),
                ('pagos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comisiones_pagadas', to='intranet.pagocomision')),
            ],
            options={
                'verbose_name': 'Comisión',
                'verbose_name_plural': 'Comisiones',
                'ordering': ['-prim_llamada_activacion'],
            },
        ),
        migrations.CreateModel(
            name='ActaRecibidoPor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.actaentrega')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActaObservaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.actaentrega')),
            ],
        ),
        migrations.CreateModel(
            name='ActaObjetivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.actaentrega')),
            ],
        ),
        migrations.AddField(
            model_name='actaentrega',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.proyecto'),
        ),
        migrations.CreateModel(
            name='ActaArchivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta_archivo', models.CharField(max_length=500)),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.actaentrega')),
            ],
        ),
        migrations.AddConstraint(
            model_name='variables_prices',
            constraint=models.UniqueConstraint(fields=('price', 'name'), name='unique_price_name'),
        ),
        migrations.AlterUniqueTogether(
            name='permisos_usuarios_precio',
            unique_together={('user', 'permiso')},
        ),
        migrations.AlterUniqueTogether(
            name='permisos_usuarios',
            unique_together={('user', 'permiso')},
        ),
    ]
