# Generated by Django 4.2.5 on 2025-08-06 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField()),
                ('version_software', models.CharField(max_length=50)),
                ('responsable', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Codigo_oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('terminal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contactanos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('correo', models.CharField(max_length=255, null=True)),
                ('asunto', models.CharField(max_length=255, null=True)),
                ('mensaje', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Corresponsal_consignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('banco', models.CharField(max_length=100)),
                ('fecha_consignacion', models.DateField()),
                ('fecha', models.DateTimeField()),
                ('responsable', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=20)),
                ('detalle', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('codigo_incocredito', models.CharField(max_length=100, null=True)),
                ('detalle_banco', models.CharField(max_length=100, null=True)),
                ('min', models.CharField(blank=True, max_length=20, null=True)),
                ('imei', models.CharField(blank=True, max_length=30, null=True)),
                ('planilla', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, null=True, unique=True)),
                ('titulo', models.CharField(max_length=255, null=True)),
                ('detalle', models.CharField(max_length=255, null=True)),
                ('precio', models.CharField(max_length=255, null=True)),
                ('carpeta', models.CharField(max_length=255, null=True)),
                ('marca', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lista_negra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lista_precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100, null=True)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dia', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.CharField(max_length=255, unique=True)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Permisos_precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.CharField(max_length=255, unique=True)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Porcentaje_comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('valor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('detalle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Traducciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=255, unique=True)),
                ('stok', models.CharField(max_length=255)),
                ('iva', models.BooleanField()),
                ('active', models.BooleanField()),
                ('tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transacciones_sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establecimiento', models.CharField(max_length=100)),
                ('codigo_aval', models.CharField(max_length=100)),
                ('codigo_incocredito', models.CharField(max_length=100)),
                ('terminal', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('hora', models.CharField(max_length=100)),
                ('nombre_convenio', models.CharField(max_length=100)),
                ('operacion', models.CharField(max_length=100)),
                ('fact_cta', models.CharField(max_length=100)),
                ('cod_aut', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('esquema', models.CharField(max_length=100)),
                ('numero_tarjeta', models.CharField(max_length=100)),
                ('comision', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Variables_prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('formula', models.TextField(null=True)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.permisos_precio')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable_corresponsal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.codigo_oficina')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Permisos_usuarios_precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_permiso', models.BooleanField()),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.permisos_precio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Permisos_usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_permiso', models.BooleanField()),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.permisos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('formula', models.TextField(null=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('price_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intranet.permisos_precio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActaRecibidoPor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.actaentrega')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActaObservaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.actaentrega')),
            ],
        ),
        migrations.CreateModel(
            name='ActaObjetivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.actaentrega')),
            ],
        ),
        migrations.AddField(
            model_name='actaentrega',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.proyecto'),
        ),
        migrations.CreateModel(
            name='ActaArchivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta_archivo', models.CharField(max_length=500)),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.actaentrega')),
            ],
        ),
        migrations.AddConstraint(
            model_name='variables_prices',
            constraint=models.UniqueConstraint(fields=('price', 'name'), name='unique_price_name'),
        ),
        migrations.AlterUniqueTogether(
            name='permisos_usuarios_precio',
            unique_together={('user', 'permiso')},
        ),
        migrations.AlterUniqueTogether(
            name='permisos_usuarios',
            unique_together={('user', 'permiso')},
        ),
    ]
