# Generated by Django 4.2.5 on 2025-10-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_create_pagocomision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comision',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Acumulada', 'Acumulada'), ('Pagada', 'Pagada'), ('Consolidada', 'Consolidada')], db_index=True, default='Pendiente', max_length=20),
        ),
    ]
