# Generated by Django 4.2 on 2023-09-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_userprofile_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traducciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=255, unique=True)),
                ('stok', models.CharField(max_length=255)),
                ('iva', models.BooleanField()),
                ('active', models.BooleanField()),
                ('tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
