# Generated by Django 4.2.5 on 2025-08-06 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_carga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista_precio',
            name='dia',
        ),
        migrations.AddField(
            model_name='lista_precio',
            name='carga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='intranet.carga'),
            preserve_default=False,
        ),
    ]
