# Generated by Django 4.2.5 on 2025-10-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0003_alter_comision_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('clave', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('valor', models.CharField(max_length=255)),
            ],
        ),
    ]
