# Generated by Django 4.2.5 on 2025-08-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0003_remove_lista_precio_dia_lista_precio_carga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corresponsal_consignacion',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
