# Generated by Django 4.2.5 on 2023-12-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0004_permisos_permisos_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('detalle', models.CharField(max_length=255)),
                ('precio', models.CharField(max_length=255)),
            ],
        ),
    ]
