# Generated by Django 4.2.5 on 2025-09-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0004_alter_corresponsal_consignacion_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corresponsal_consignacion',
            name='detalle_banco',
            field=models.TextField(null=True),
        ),
    ]
