# Generated by Django 4.2.5 on 2025-11-07 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0005_alter_comision_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocomision',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagocomision',
            name='fecha_pago',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
