# Generated by Django 4.2.5 on 2025-09-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0005_alter_corresponsal_consignacion_detalle_banco'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteDetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha de la venta')),
                ('imei', models.CharField(help_text='IMEI único del equipo', max_length=50, unique=True)),
                ('modelo_equipo', models.CharField(max_length=255)),
                ('sucursal', models.CharField(max_length=100)),
                ('tipo_producto', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_venta_original', models.CharField(help_text="El 'Tipo de venta' original del Excel", max_length=100)),
                ('asesor', models.CharField(blank=True, max_length=150, null=True)),
                ('canal', models.CharField(blank=True, max_length=100, null=True)),
                ('tiket_venta', models.CharField(blank=True, max_length=100, null=True)),
                ('costo_equipo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('incentivo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('clasificacion_venta', models.CharField(help_text='Categoría calculada (Sell In, Sell Out, Inventario)', max_length=50)),
                ('tipo_vendedor', models.CharField(blank=True, help_text='Categoría adicional para Sell Out (UP, Freelance, etc.)', max_length=50, null=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se cargó el registro')),
            ],
            options={
                'verbose_name': 'Detalle de Venta para Reporte',
                'verbose_name_plural': 'Detalles de Venta para Reportes',
                'ordering': ['-fecha'],
            },
        ),
    ]
