# Generated by Django 4.2.5 on 2023-12-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0005_imagenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenes',
            name='carpeta',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='detalle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='precio',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='titulo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='url',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
