# Generated by Django 4.2.5 on 2023-12-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0006_imagenes_carpeta_alter_imagenes_detalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenes',
            name='marca',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
