# Generated by Django 4.2.5 on 2025-11-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0006_pagocomision_observacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocomision',
            name='comprobante_url',
            field=models.CharField(blank=True, help_text='Nombre del archivo del comprobante almacenado en SharePoint', max_length=255, null=True),
        ),
    ]
