# Generated by Django 4.2.5 on 2023-12-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0007_imagenes_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactanos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('correo', models.CharField(max_length=255, null=True)),
                ('asunto', models.CharField(max_length=255, null=True)),
                ('mensaje', models.TextField(null=True)),
            ],
        ),
    ]
