# Generated by Django 4.2.5 on 2025-11-21 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intranet', '0007_pagocomision_comprobante_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaAsignada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_comisiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'ruta')},
            },
        ),
    ]
