# Generated by Django 4.2.5 on 2025-11-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0008_rutaasignada'),
    ]

    operations = [
        migrations.CreateModel(
            name='IvaExcepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=255, unique=True)),
                ('tipo', models.CharField(default='prepago', max_length=50)),
            ],
        ),
    ]
