# Generated by Django 4.2.5 on 2025-12-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0009_ivaexcepcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
