# Generated by Django 4.2.5 on 2024-01-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0009_formula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
