# Generated by Django 4.2.5 on 2024-01-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0010_alter_formula_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista_precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'unique_together': {('producto', 'nombre')},
            },
        ),
    ]
