# Generated by Django 4.2.5 on 2025-12-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0010_comision_observacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransparencyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_type', models.CharField(choices=[('corruption', 'Corrupción / Corruption'), ('transnational_bribery', 'Soborno transnacional / Transnational bribery'), ('fraud', 'Fraude / Fraud'), ('misuse_resources', 'Uso inadecuado de recursos / Misuse of resources'), ('regulatory_irregularities', 'Irregularidades en el cumplimiento de normas / Regulatory irregularities'), ('money_laundering', 'Lavado de activos / Money laundering'), ('terrorism_financing', 'Financiación del terrorismo / Terrorism financing'), ('wmd_financing', 'Financiamiento de armas de destrucción masiva / WMD financing'), ('other', 'Otros / Other')], default='other', max_length=64)),
                ('description', models.TextField()),
                ('event_date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Departamento / Estado')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('people_involved', models.TextField(blank=True)),
                ('supports_text', models.TextField(blank=True)),
                ('wants_identification', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('id_number', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('locale', models.CharField(blank=True, max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('attachments_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
