# Generated by Django 4.2.5 on 2026-01-22 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intranet', '0011_transparencyreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comision',
            name='comision_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='ComisionCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mes_detectado', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('processing', 'Procesando'), ('success', 'Exitosa'), ('error', 'Error'), ('rolled_back', 'Revertida')], db_index=True, default='processing', max_length=20)),
                ('registros_creados', models.PositiveIntegerField(default=0)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas_comisiones', to=settings.AUTH_USER_MODEL)),
                ('rolled_back_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollbacks_comisiones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comision',
            name='carga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comisiones', to='intranet.comisioncarga'),
        ),
    ]
