# Generated by Django 4.2.5 on 2024-01-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0011_lista_precio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lista_precio',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lista_precio',
            name='dia',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='lista_precio',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lista_precio',
            name='producto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='lista_precio',
            constraint=models.UniqueConstraint(fields=('producto', 'nombre', 'dia'), name='unique_producto_nombre_dia'),
        ),
    ]
