# Generated by Django 4.2.5 on 2024-02-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0012_alter_lista_precio_unique_together_lista_precio_dia_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lista_precio',
            name='unique_producto_nombre_dia',
        ),
        migrations.AlterField(
            model_name='lista_precio',
            name='dia',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
