# Generated by Django 4.2.5 on 2026-03-09 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intranet', '0012_alter_comision_comision_final_comisioncarga_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('entrada_1', models.TimeField()),
                ('salida_1', models.TimeField()),
                ('entrada_2', models.TimeField(blank=True, null=True)),
                ('salida_2', models.TimeField(blank=True, null=True)),
                ('almuerzo_inicio', models.TimeField(blank=True, null=True)),
                ('almuerzo_fin', models.TimeField(blank=True, null=True)),
                ('nota', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', 'user_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(fields=('user', 'fecha'), name='unique_turno_user_fecha'),
        ),
    ]
