# Generated by Django 4.2.5 on 2026-03-09 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intranet', '0013_turno_turno_unique_turno_user_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaTurnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TurnoPlanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('entrada_1', models.TimeField()),
                ('salida_1', models.TimeField()),
                ('entrada_2', models.TimeField(blank=True, null=True)),
                ('salida_2', models.TimeField(blank=True, null=True)),
                ('almuerzo_inicio', models.TimeField(blank=True, null=True)),
                ('almuerzo_fin', models.TimeField(blank=True, null=True)),
                ('nota', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha', 'persona_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='turno',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='turno',
            name='unique_turno_user_fecha',
        ),
        migrations.AddField(
            model_name='turnoplanner',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_planner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turnoplanner',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='intranet.personaturnos'),
        ),
        migrations.AddField(
            model_name='personaturnos',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas_turnos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='turnoplanner',
            constraint=models.UniqueConstraint(fields=('owner', 'persona', 'fecha'), name='unique_owner_persona_fecha_turnoplanner'),
        ),
        migrations.AddConstraint(
            model_name='personaturnos',
            constraint=models.UniqueConstraint(fields=('owner', 'nombre'), name='unique_owner_nombre_persona_turnos'),
        ),
    ]
