# Generated by Django 4.2.5 on 2026-03-09 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intranet', '0014_personaturnos_turnoplanner_alter_turno_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=120)),
                ('entrada_1', models.TimeField()),
                ('salida_1', models.TimeField()),
                ('entrada_2', models.TimeField(blank=True, null=True)),
                ('salida_2', models.TimeField(blank=True, null=True)),
                ('almuerzo_inicio', models.TimeField(blank=True, null=True)),
                ('almuerzo_fin', models.TimeField(blank=True, null=True)),
                ('color', models.CharField(default='#0d6efd', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_plantillas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='GrupoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('color', models.CharField(default='#198754', max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_grupos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='turnoplantilla',
            constraint=models.UniqueConstraint(fields=('owner', 'codigo'), name='unique_owner_plantilla_codigo'),
        ),
        migrations.AddConstraint(
            model_name='grupotrabajo',
            constraint=models.UniqueConstraint(fields=('owner', 'nombre'), name='unique_owner_grupo_nombre'),
        ),
    ]
