# Generated by Django 4.2.5 on 2024-02-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0014_permisos_precio_permisos_usuarios_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porcentaje_comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('valor', models.CharField(max_length=255)),
            ],
        ),
    ]
