# Generated by Django 4.2.5 on 2024-05-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0015_porcentaje_comision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacciones_sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establecimiento', models.CharField(max_length=100)),
                ('codigo_aval', models.DecimalField(decimal_places=0, max_digits=10)),
                ('codigo_incocredito', models.DecimalField(decimal_places=0, max_digits=10)),
                ('terminal', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('hora', models.CharField(max_length=100)),
                ('nombre_convenio', models.CharField(max_length=100)),
                ('operacion', models.CharField(max_length=100)),
                ('fact_cta', models.CharField(max_length=100)),
                ('cod_aut', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('esquema', models.CharField(max_length=100)),
                ('numero_tarjeta', models.CharField(max_length=100)),
                ('comision', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
