# Generated by Django 4.2.5 on 2024-05-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0016_transacciones_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciones_sucursal',
            name='cod_aut',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transacciones_sucursal',
            name='codigo_aval',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transacciones_sucursal',
            name='codigo_incocredito',
            field=models.CharField(max_length=100),
        ),
    ]
