# Generated by Django 4.2.5 on 2024-05-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0017_alter_transacciones_sucursal_cod_aut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='codigo_oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('terminal', models.CharField(max_length=100)),
            ],
        ),
    ]
