# Generated by Django 4.2.5 on 2024-07-25 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intranet', '0018_codigo_oficina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corresponsal_consignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('banco', models.CharField(max_length=100)),
                ('fecha_consignacion', models.DateField()),
                ('fecha', models.DateTimeField()),
                ('responsable', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=20)),
                ('detalle', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable_corresponsal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.codigo_oficina')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
