# Generated by Django 4.2.5 on 2024-07-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0019_corresponsal_consignacion_responsable_corresponsal'),
    ]

    operations = [
        migrations.AddField(
            model_name='corresponsal_consignacion',
            name='codigo_incocredito',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
