# Generated by Django 4.2.5 on 2024-09-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0020_corresponsal_consignacion_codigo_incocredito'),
    ]

    operations = [
        migrations.AddField(
            model_name='corresponsal_consignacion',
            name='detalle_banco',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
