# Generated by Django 4.2.5 on 2024-12-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0021_corresponsal_consignacion_detalle_banco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista_negra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
