# Generated by Django 4.2.5 on 2025-01-13 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0022_lista_negra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variables_prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('formula', models.TextField(null=True)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.permisos_precio')),
            ],
        ),
    ]
