# Generated by Django 4.2.5 on 2025-01-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0023_variables_prices'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='variables_prices',
            constraint=models.UniqueConstraint(fields=('price', 'name'), name='unique_price_name'),
        ),
    ]
