# Generated by Django 4.2.5 on 2025-01-14 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0024_variables_prices_unique_price_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='price_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intranet.permisos_precio'),
        ),
    ]
