# Generated by Django 4.2.5 on 2025-08-06 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intranet', '0028_imagenlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_precio',
            name='dia',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.AddField(
            model_name='lista_precio',
            name='carga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='intranet.carga'),
        ),
    ]
